backend:
  name: git-gateway
  branch: main

site_url: https://trocosmm.shop

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "configuracoes"
    label: "Configurações do Site"
    description: "Edite aqui as configurações gerais e a lista de produtos."
    files:
      - name: "settings"
        label: "Configurações Gerais"
        file: "_data/settings.json"
        fields:
          - { label: "Título Principal do Site", name: "title", widget: "string" }
          - { label: "Slogan abaixo do Título", name: "tagline", widget: "string" }
          - label: "Links de Suporte"
            name: "links"
            widget: "object"
            fields:
              - { label: "Link do Grupo WhatsApp", name: "group_whatsapp", widget: "string" }
              - { label: "Link do Suporte Telegram", name: "support_telegram", widget: "string" }
              - { label: "Número do Suporte WhatsApp (com +55)", name: "support_whatsapp_number", widget: "string" }
          - label: "Cupom de Desconto"
            name: "coupon"
            widget: "object"
            fields:
              - { label: "Código do Cupom (ex: DESC10)", name: "code", widget: "string" }
              - { label: "Percentagem de Desconto (ex: 0.1 para 10%)", name: "percentage", widget: "number" }

      - name: "products"
        label: "Serviços SMM"
        file: "_data/products.json"
        fields:
          - name: "items"
            label: "Lista de Serviços"
            widget: "list"
            summary: "{{fields.name}} - Categoria: {{fields.category}}"
            fields:
              - { label: "ID (número único, não repita)", name: "id", widget: "number" }
              - { label: "Nome do Serviço", name: "name", widget: "string" }
              - { label: "Ícone (ex: fab fa-instagram)", name: "icon", widget: "string" }
              - label: "Categoria"
                name: "category"
                widget: "select"
                options: ["instagram", "tiktok", "youtube", "facebook", "twitter"]
              - { label: "Descrição Curta", name: "description", widget: "string" }
              - label: "Variações do Serviço"
                name: "variations"
                widget: "list"
                summary: "{{fields.name}} - R$ {{fields.price}} por mil"
                fields:
                  - { label: "Nome da Variação", name: "name", widget: "string" }
                  - { label: "Preço (por 1000 unidades)", name: "price", widget: "number" }
                  - { label: "Detalhes (texto curto)", name: "details", widget: "string" }
                  - { label: "Nota Importante (texto curto)", name: "important", widget: "string" }